/*
js object containing info on elements
Kept separate from table.js for easier readability/editing
Currently contains element's: atomic number, symbol, name, & group
    Element info in nested object (symbol is also the property)
*/
const elements_main={
    H:{
        number:"1",
        symbol:"H",
        name:"Hydrogen",
        group: "Nonmetal",
        group_no: 3,},
    He: {
        number:"2",
        symbol:"He",
        name:"Helium",
        group:"Noble Gas",
        group_no: 8,},
    Li: {
        number:"3",
        symbol:"Li",
        name:"Lithium",
        group:"Alkali Metal",
        group_no: 1,},    
    Be: {
        number:"4",
        symbol:"Be",
        name:"Beryllium",
        group:"Alkali Earth Metal",
        group_no: 2,},
    B: {
        number:"5",
        symbol:"B",
        name:"Boron",
        group:"Metalloid",
        group_no: 4,},
    C: {
        number:"6",
        symbol:"C",
        name:"Carbon",
        group:"Nonmetal",
        group_no: 3,},
    N: {
        number:"7",
        symbol:"N",
        name:"nitrogen",
        group:"Nonmetal",
        group_no: 3,},
    O: {
        number:"8",
        symbol:"O",
        name:"Oxygen",
        group:"Nonmetal",
        group_no: 3,},
    F: {
        number:"9",
        symbol:"F",
        name:"Fluorine",
        group:"Halogen",
        group_no: 7,},
    Ne: {
        number:"10",
        symbol:"Ne",
        name:"Neon",
        group:"Noble Gas",
        group_no: 8,},
    Na: {
        number:"11",
        symbol:"Na",
        name:"Sodium",
        group:"Alkali Metal",
        group_no: 1,},
    Mg: {
        number:"12",
        symbol:"Mg",
        name:"Magnesium",
        group:"Alkaline Earth Metal",
        group_no: 2,},
    Al: {
        number:"13",
        symbol:"Al",
        name:"Aluminum",
        group:"Post-Transition Metal",
        group_no: 5,},
    Si: {
        number:"14",
        symbol:"Si",
        name:"Silicon",
        group:"Metalloid",
        group_no: 4,},
    P: {
        number:"15",
        symbol:"P",
        name:"Phosphorus",
        group:"Nonmetal",
        group_no: 3,},
    S: {
        number:"16",
        symbol:"S",
        name:"Sulfur",
        group:"Nonmetal",
        group_no: 3,},
    Cl: {
        number:"17",
        symbol:"Cl",
        name:"Chlorine",
        group:"Halogen",
        group_no: 7,},
    Ar: {
        number:"18",
        symbol:"Ar",
        name:"Argon",
        group:"Noble Gas",
        group_no: 8,},
    K: {
        number:"19",
        symbol:"K",
        name:"Potassium",
        group:"Alkali Metal",
        group_no: 1,},
    Ca: {
        number:"20",
        symbol:"Ca",
        name:"Calcium",
        group:"Alkali Earth Metal",
        group_no: 2,},
    Sc: {
        number:"21",
        symbol:"Sc",
        name:"Scandium",
        group:"Transition Metal",
        group_no: 6,},
    Ti: {
        number:"22",
        symbol:"Ti",
        name:"Titanium",
        group:"Transition Metal",
        group_no: 6,},
    V: {
        number:"23",
        symbol:"V",
        name:"Vanadium",
        group:"Transition Metal",
        group_no: 6,},
    Cr: {
        number:"24",
        symbol:"Cr",
        name:"Chromium",
        group:"Transition Metal",
        group_no: 6,},
    Mn: {
        number:"25",
        symbol:"Mn",
        name:"Manganese",
        group:"Transition Metal",
        group_no: 6,},
    Fe: {
        number:"26",
        symbol:"Fe",
        name:"Iron",
        group:"Transition Metal",
        group_no: 6,},
    Co: {
        number:"27",
        symbol:"Co",
        name:"Cobalt",
        group:"Transition Metal",
        group_no: 6,},
    Ni: {
        number:"28",
        symbol:"Ni",
        name:"Nickel",
        group:"Transition Metal",
        group_no: 6,},
    Cu: {
        number:"29",
        symbol:"Cu",
        name:"Copper",
        group:"Transition Metal",
        group_no: 6,},
    Zn: {
        number:"30",
        symbol:"Zn",
        name:"Zinc",
        group:"Transition Metal",
        group_no: 6,},
    Ga: {
        number:"31",
        symbol:"Ga",
        name:"Gallium",
        group:"Post-Transition Metal",
        group_no: 5,},
    Ge: {
        number:"32",
        symbol:"Ge",
        name:"Germanium",
        group:"Metalloid",
        group_no: 4,},
    As: {
        number:"33",
        symbol:"As",
        name:"Arsenic",
        group:"Transition Metal",
        group_no: 6,},
    Se: {
        number:"34",
        symbol:"Se",
        name:"Selenium",
        group:"Nonmetal",
        group_no: 3,},
    Br: {
        number:"35",
        symbol:"Br",
        name:"Bromine",
        group:"Halogen",
        group_no: 7,},
    Kr: {
        number:"36",
        symbol:"Kr",
        name:"Krypton",
        group:"Noble Gas",
        group_no: 8,},
    Rb: {
        number:"37",
        symbol:"Rb",
        name:"Rubidium",
        group:"Alkali Metal",
        group_no: 1,},
    Sr: {
        number:"38",
        symbol:"Sr",
        name:"Strontium",
        group:"Alkali Earth Metal",
        group_no: 2,},
    Y: {
        number:"39",
        symbol:"Y",
        name:"Yttrium",
        group:"Transition Metal",
        group_no: 6,},
    Zr: {
        number:"40",
        symbol:"Zr",
        name:"Zirconium",
        group:"Transition Metal",
        group_no: 6,},
    Nb: {
        number:"41",
        symbol:"Nb",
        name:"Niobium",
        group:"Transition Metal",
        group_no: 6,},
    Mo: {
        number:"42",
        symbol:"Mo",
        name:"Molybdenum",
        group:"Transition Metal",
        group_no: 6,},
    Tc: {
        number:"43",
        symbol:"Tc",
        name:"Technetium",
        group:"Transition Metal",
        group_no: 6,},
    Ru: {
        number:"44",
        symbol:"Ru",
        name:"Ruthenium",
        group:"Transition Metal",
        group_no: 6,},
    Rh: {
        number:"45",
        symbol:"Rh",
        name:"Rhodium",
        group:"Transition Metal",
        group_no: 6,},
    Pd: {
        number:"46",
        symbol:"Pd",
        name:"Palladium",
        group:"Transition Metal",
        group_no: 6,},
    Ag: {
        number:"47",
        symbol:"Ag",
        name:"Silver",
        group:"Transition Metal",
        group_no: 6,},
    Cd: {
        number:"48",
        symbol:"Cd",
        name:"Cadmium",
        group:"Transition Metal",
        group_no: 6,},
    In: {
        number:"49",
        symbol:"In",
        name:"Indium",
        group:"Post-Transition Metal",
        group_no: 5,},
    Sn: {
        number:"50",
        symbol:"Sn",
        name:"Tin",
        group:"Post-Transition Metal",
        group_no: 5,},
    Sb: {
        number:"51",
        symbol:"Sb",
        name:"Antimony",
        group:"Metalloid",
        group_no: 4,},
    Te: {
        number:"52",
        symbol:"Te",
        name:"Tellurium",
        group:"Metalloid",
        group_no: 4,},
    I: {
        number:"53",
        symbol:"I",
        name:"Iodine",
        group:"Halogen",
        group_no: 7,},
    Xe: {
        number:"54",
        symbol:"Xe",
        name:"Xenon",
        group:"Noble Gas",
        group_no: 8,},
    Cs: {
        number:"55",
        symbol:"Cs",
        name:"Caesium",
        group:"Alkali Metal",
        group_no: 1,},
    Ba: {
        number:"56",
        symbol:"Ba",
        name:"Barium",
        group:"Alkali Earth Metal",
        group_no: 2,},
    La: {
        number:"57",
        symbol:"La",
        name:"Lanthanum",
        group:"Lanthanide",
        group_no: 9,},
    Hf: {
        number:"72",
        symbol:"Hf",
        name:"Hafnium",
        group:"Transition Metal",
        group_no: 6,},
    Ta: {
        number:"73",
        symbol:"Ta",
        name:"Tantalum",
        group:"Transition Metal",
        group_no: 6,},
    W: {
        number:"74",
        symbol:"W",
        name:"Tungsten",
        group:"Transition Metal",
        group_no: 6,},
    Re: {
        number:"75",
        symbol:"Re",
        name:"Rhenium",
        group:"Transition Metal",
        group_no: 6,},
    Os: {
        number:"76",
        symbol:"Os",
        name:"Osmium",
        group:"Transition Metal",
        group_no: 6,},
    Ir: {
        number:"77",
        symbol:"Ir",
        name:"Iridium",
        group:"Transition Metal",
        group_no: 6,},
    Pt: {
        number:"78",
        symbol:"Pt",
        name:"Platinum",
        group:"Transition Metal",
        group_no: 6,}, 
    Au: {
        number:"79",
        symbol:"Au",
        name:"Gold",
        group:"Transition Metal",
        group_no: 6,},  
    Hg: {
        number:"80",
        symbol:"Hg",
        name:"Mercury",
        group:"Transition Metal",
        group_no: 6,},
    Tl: {
        number:"81",
        symbol:"Tl",
        name:"Thallium",
        group:"Post-Transition Metal",
        group_no: 5,},
    Pb: {
        number:"82",
        symbol:"Pb",
        name:"Lead",
        group:"Post-Transition Metal",
        group_no: 5,},
    Bi: {
        number:"83",
        symbol:"Bi",
        name:"Bismuth",
        group:"Post-Transition Metal",
        group_no: 5,},
    Po: {
        number:"84",
        symbol:"Po",
        name:"Polonium",
        group:"Post-Transition Metal",
        group_no: 5,},
    At: {
        number:"85",
        symbol:"At",
        name:"Astatine",
        group:"Post-Transition Metal",
        group_no: 5,},
    Rn: {
        number:"86",
        symbol:"Rn",
        name:"Radon",
        group:"Noble Gas",
        group_no: 8,},
    Fr: {
        number:"87",
        symbol:"Fr",
        name:"Francium",
        group:"Alkali Metal",
        group_no: 1,},
    Ra: {
        number:"88",
        symbol:"Ra",
        name:"Radium",
        group:"Alkali Earth Metal",
        group_no: 2,},
    Ac: {
        number:"89",
        symbol:"Ac",
        name:"Actinium",
        group:"Actinide",
        group_no: 10,},
    Rf: {
        number:"104",
        symbol:"Rf",
        name:"Rutherfordium",
        group:"Transition Metal",
        group_no: 6,},
    Db: {
        number:"105",
        symbol:"Db",
        name:"Dubnium",
        group:"Transition Metal",
        group_no: 6,},
    Sg: {
        number:"106",
        symbol:"Sg",
        name:"Seaborgium",
        group:"Transition Metal",
        group_no: 6,},
    Bh: {
        number:"107",
        symbol:"Bh",
        name:"Bohrium",
        group:"Transition Metal",
        group_no: 6,},
    Hs: {
        number:"108",
        symbol:"Hs",
        name:"Hassium",
        group:"Transition Metal",
        group_no: 6,},
    Mt: {
        number:"109",
        symbol:"Mt",
        name:"Meitnerium",
        group:"Transition Metal",
        group_no: 6,},
    Ds: {
        number:"110",
        symbol:"Ds",
        name:"Darmstadtium",
        group:"Transition Metal",
        group_no: 6,},
    Rg: {
        number:"111",
        symbol:"Rg",
        name:"Roentgenium",
        group:"Transition Metal",
        group_no: 6,},
    Cn: {
        number:"112",
        symbol:"Cn",
        name:"Copernicium",
        group:"Transition Metal",
        group_no: 6,},
    Nh: {
        number:"113",
        symbol:"Nh",
        name:"Nihonium",
        group:"Post-Transition Metal",
        group_no: 5,},
    Fl: {
        number:"114",
        symbol:"Fl",
        name:"Flerovium",
        group:"Post-Transition Metal",
        group_no: 5,},
    Mc: {
        number:"115",
        symbol:"Mc",
        name:"Moscovium",
        group:"Post-Transition Metal",
        group_no: 5,},
    Lv: {
        number:"116",
        symbol:"Lv",
        name:"Livermorium",
        group:"Post-Transition Metal",
        group_no: 5,},
    Ts: {
        number:"117",
        symbol:"Ts",
        name:"Tennessine",
        group:"Post-Transition Metal",
        group_no: 5,},
    Og: {
        number:"118",
        symbol:"Og",
        name:"Oganesson",
        group:"Noble Gas",
        group_no: 8,},
    }
const elements_lanth_act={
    Ce: {
        number:"58",
        symbol:"Ce",
        name:"Cerium",
        group:"Lanthanide",
        group_no: 9,},
    Pr: {
        number:"59",
        symbol:"Pr",
        name:"Praseodymium",
        group:"Lanthanide",
        group_no: 9,},
    Nd: {
        number:"60",
        symbol:"Nd",
        name:"Neodymium",
        group:"Lanthanide",
        group_no: 9,},
    Pm: {
        number:"61",
        symbol:"Pm",
        name:"Promethium",
        group:"Lanthanide",
        group_no: 9,},
    Sm: {
        number:"62",
        symbol:"Sm",
        name:"Samarium",
        group:"Lanthanide",
        group_no: 9,},
    Eu: {
        number:"63",
        symbol:"Eu",
        name:"Europium",
        group:"Lanthanide",
        group_no: 9,},
    Gd: {
        number:"64",
        symbol:"Gd",
        name:"Gadolinium",
        group:"Lanthanide",
        group_no: 9,},
    Tb: {
        number:"65",
        symbol:"Tb",
        name:"Terbium",
        group:"Lanthanide",
        group_no: 9,},
    Dy: {
        number:"66",
        symbol:"Dy",
        name:"Dysprosium",
        group:"Lanthanide",
        group_no: 9,},
    Ho: {
        number:"67",
        symbol:"Ho",
        name:"Holmium",
        group:"Lanthanide",
        group_no: 9,},
    Er: {
        number:"68",
        symbol:"Er",
        name:"Erbium",
        group:"Lanthanide",
        group_no: 9,},
    Tm: {
        number:"69",
        symbol:"Tm",
        name:"Thulium",
        group:"Lanthanide",
        group_no: 9,},
    Yb: {
        number:"70",
        symbol:"Yb",
        name:"Ytterbium",
        group:"Lanthanide",
        group_no: 9,},
    Lu: {
        number:"71",
        symbol:"Lu",
        name:"Lutetium",
        group:"Lanthanide",
        group_no: 9,},
    Th: {
        number:"90",
        symbol:"Th",
        name:"Thorium",
        group:"Actinide",
        group_no: 10,},
    Pa: {
        number:"91",
        symbol:"Pa",
        name:"Protactinium",
        group:"Actinide",
        group_no: 10,},
    U: {
        number:"92",
        symbol:"Ur",
        name:"Uranium",
        group:"Actinide",
        group_no: 10,},
    Np: {
        number:"93",
        symbol:"Np",
        name:"Neptunium",
        group:"Actinide",
        group_no: 10,},
    Pu: {
        number:"94",
        symbol:"Pu",
        name:"Plutonium",
        group:"Actinide",
        group_no: 10,},
    Am: {
        number:"95",
        symbol:"Am",
        name:"Americium",
        group:"Actinide",
        group_no: 10,},
    Cm: {
        number:"96",
        symbol:"Cm",
        name:"Curium",
        group:"Actinide",
        group_no: 10,},
    Bk: {
        number:"97",
        symbol:"Bk",
        name:"Berkelium",
        group:"Actinide",
        group_no: 10,},
    Cf: {
        number:"98",
        symbol:"Cf",
        name:"Californium",
        group:"Actinide",
        group_no: 10,},
    Es: {
        number:"99",
        symbol:"Es",
        name:"Einsteinium",
        group:"Actinide",
        group_no: 10,},
    Fm: {
        number:"100",
        symbol:"Fm",
        name:"Fermium",
        group:"Actinide",
        group_no: 10,},
    Md: {
        number:"101",
        symbol:"Md",
        name:"Mendelevium",
        group:"Actinide",
        group_no: 10,},
    No: {
        number:"102",
        symbol:"No",
        name:"Nobelium",
        group:"Actinide",
        group_no: 10,},
    Lr: {
        number:"103",
        symbol:"Lr",
        name:"Lawrencium",
        group:"Actinide",
        group_no: 10,},}